In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3,4],[4,5,6,7]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [4]:
# get dimension
a.ndim

1

In [5]:
# get shape
b.shape

(2, 4)

In [6]:
#get type
a.dtype

dtype('int32')

In [7]:
# get size
a.itemsize

4

In [8]:
# get totalsize
a.nbytes

12

In [9]:
c = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(c)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [10]:
# get specific elemnet [r,c]
c[1,3]

6

In [11]:
c[1,5] = 20
print(c)

IndexError: index 5 is out of bounds for axis 1 with size 5

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [15]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [16]:
np

<module 'numpy' from 'C:\\Users\\Ashish\\Anaconda3\\envs\\python\\lib\\site-packages\\numpy\\__init__.py'>